### ISSUE TITLE
Situational Indium Dependency

### ISSUE THREAD

**Issue by riverbanksquid** [Juuxel/PaintersBlocks#4]
Just thought I'd mention that since this mod uses the Fabric rendering API it requires Indium to be installed if Sodium is present, or all the glowing blocks will have missing textures. It took me some messing around to figure that out, but it was a super easy fix once I did, so it might help someone else if you added a note about it to the curseforge description.

This mod is totally worth having biome blending turned off + I'm glad I was able to fix the missing textures as well! Thank you for the cool cubes. 😎

**Comment by Juuxel** [comment]
Thanks, I added that to the CF description.
