### ISSUE TITLE
Crash on Startup due to conflict between Indium and FREX

### ISSUE THREAD

**Issue by TheButterbrotMan** [Juuxel/PaintersBlocks#5]
Hello, my game is crashing on startup.

https://pastebin.com/QTQqppBa

**Comment by Juuxel** [comment]
Oh dear, this is a mod conflict between FREX (which I use in PB) and Indium. Not something I can help with, sadly, so try seeking help from those projects.

**Comment by Juuxel** [comment]
Should be fixed in 39c40ee7c50043ef2b509c9f80b381ab5ef545e9 since I removed JMX and FREX from Painter's Blocks.
